const img4 = "https://firebasestorage.googleapis.com/v0/b/di-giovanni-website.appspot.com/o/pexels-kindel-media-7979442%20(1).jpg?alt=media&token=51f7543c-f0d9-4fda-aa17-7e80b13f4beb";
const img5 = "https://firebasestorage.googleapis.com/v0/b/di-giovanni-website.appspot.com/o/pexels-rodnae-productions-7841410.jpg?alt=media&token=ba74a485-f1e3-4ac2-9fa4-c32d2b84f8bb";
const img6 = "https://firebasestorage.googleapis.com/v0/b/di-giovanni-website.appspot.com/o/pexels-pavel-danilyuk-8112168%20(1).jpg?alt=media&token=956bcd15-3e6b-4f27-8579-2c4514569e10";
const img7 = "https://firebasestorage.googleapis.com/v0/b/di-giovanni-website.appspot.com/o/pexels-rodnae-productions-7841840.jpg?alt=media&token=dc8a2d72-2a40-421d-911c-9be066c99767";
const img8 = "https://firebasestorage.googleapis.com/v0/b/di-giovanni-website.appspot.com/o/pexels-mikhail-nilov-8730374%20(1).jpg?alt=media&token=8645b4b5-f00d-4757-a2c2-feef687d09c6";

const services = [
    {
        id: "1",
        route: "/atuacao/1",
        img: img8,
        title: "Contencioso Tributário (Judicial e Administrativo)",
        description: "A prática tem como objetivo prover alta qualidade de serviços legais a clientes brasileiros e estrangeiros em suporte a diversas atividades comerciais nas principais indústrias e setores.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel eleifend enim. Sed dictum id justo quis blandit. Suspendisse potenti. Vivamus at dui felis. Morbi sodales, erat eget commodo faucibus, urna tortor sodales nibh, sit amet eleifend orci lectus quis magna. Ut pretium aliquam lorem, a cursus sem vestibulum ac. Sed vulputate, massa ut euismod eleifend, sem eros mattis nulla, sit amet porta ex felis ut diam. <br/><br/>Aenean blandit feugiat ante, a faucibus lacus feugiat varius. Suspendisse tincidunt luctus fringilla. Vivamus sed ipsum ut quam commodo sagittis. Proin posuere sit amet odio eu molestie. Mauris ullamcorper mi a elit posuere dictum. Sed id urna vehicula, mattis libero non, rutrum mauris. Cras eu dolor vitae ex aliquam bibendum in nec augue. Ut sit amet faucibus nulla. Cras magna mauris, lacinia et ex ut, ultricies tincidunt dolor. Etiam viverra faucibus ex, id pharetra lorem ornare in. Quisque sit amet semper tortor. Donec rhoncus diam erat, et lacinia diam mattis id. Fusce cursus diam quis fermentum porta. Maecenas rutrum ipsum rutrum suscipit egestas. <br/><br/>Phasellus venenatis tortor orci, ut feugiat justo efficitur sit amet. Vivamus cursus semper tellus, eget sodales quam tincidunt fermentum. Aenean elementum lobortis felis, eget vehicula lorem sagittis sit amet. Etiam sit amet erat consequat, congue nulla id, iaculis nunc. Donec eleifend libero sit amet turpis volutpat lobortis. Vivamus cursus enim in libero maximus finibus. Pellentesque accumsan laoreet blandit. Phasellus dolor felis, malesuada sit amet sapien vel, congue condimentum tellus. Nulla imperdiet tempor lectus. Etiam fringilla gravida risus id molestie. Phasellus ultrices sed arcu ac semper."
    },
    {
        id: "2",
        route: "/atuacao/2",
        img: img4,
        title: "Gestão de departamentos Jurídicos e Tributários",
        description: "Tecnologia e conteúdo confiável são fortes aliados para apoiar os departamentos jurídicos das corporações, garantindo uma gestão jurídica eficiente.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel eleifend enim. Sed dictum id justo quis blandit. Suspendisse potenti. Vivamus at dui felis. Morbi sodales, erat eget commodo faucibus, urna tortor sodales nibh, sit amet eleifend orci lectus quis magna. Ut pretium aliquam lorem, a cursus sem vestibulum ac. Sed vulputate, massa ut euismod eleifend, sem eros mattis nulla, sit amet porta ex felis ut diam. <br/><br/>Aenean blandit feugiat ante, a faucibus lacus feugiat varius. Suspendisse tincidunt luctus fringilla. Vivamus sed ipsum ut quam commodo sagittis. Proin posuere sit amet odio eu molestie. Mauris ullamcorper mi a elit posuere dictum. Sed id urna vehicula, mattis libero non, rutrum mauris. Cras eu dolor vitae ex aliquam bibendum in nec augue. Ut sit amet faucibus nulla. Cras magna mauris, lacinia et ex ut, ultricies tincidunt dolor. Etiam viverra faucibus ex, id pharetra lorem ornare in. Quisque sit amet semper tortor. Donec rhoncus diam erat, et lacinia diam mattis id. Fusce cursus diam quis fermentum porta. Maecenas rutrum ipsum rutrum suscipit egestas. <br/><br/>Phasellus venenatis tortor orci, ut feugiat justo efficitur sit amet. Vivamus cursus semper tellus, eget sodales quam tincidunt fermentum. Aenean elementum lobortis felis, eget vehicula lorem sagittis sit amet. Etiam sit amet erat consequat, congue nulla id, iaculis nunc. Donec eleifend libero sit amet turpis volutpat lobortis. Vivamus cursus enim in libero maximus finibus. Pellentesque accumsan laoreet blandit. Phasellus dolor felis, malesuada sit amet sapien vel, congue condimentum tellus. Nulla imperdiet tempor lectus. Etiam fringilla gravida risus id molestie. Phasellus ultrices sed arcu ac semper."
    },
    {
        id: "3",
        route: "/atuacao/3",
        img: img5,
        title: "Consultoria Tributária, due diligence",
        description: "Quando se inicia um processo de Due Diligence, o resultado fatalmente será um entendimento maior do negócio, tanto para o investidor quanto para a empresa-alvo.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel eleifend enim. Sed dictum id justo quis blandit. Suspendisse potenti. Vivamus at dui felis. Morbi sodales, erat eget commodo faucibus, urna tortor sodales nibh, sit amet eleifend orci lectus quis magna. Ut pretium aliquam lorem, a cursus sem vestibulum ac. Sed vulputate, massa ut euismod eleifend, sem eros mattis nulla, sit amet porta ex felis ut diam. <br/><br/>Aenean blandit feugiat ante, a faucibus lacus feugiat varius. Suspendisse tincidunt luctus fringilla. Vivamus sed ipsum ut quam commodo sagittis. Proin posuere sit amet odio eu molestie. Mauris ullamcorper mi a elit posuere dictum. Sed id urna vehicula, mattis libero non, rutrum mauris. Cras eu dolor vitae ex aliquam bibendum in nec augue. Ut sit amet faucibus nulla. Cras magna mauris, lacinia et ex ut, ultricies tincidunt dolor. Etiam viverra faucibus ex, id pharetra lorem ornare in. Quisque sit amet semper tortor. Donec rhoncus diam erat, et lacinia diam mattis id. Fusce cursus diam quis fermentum porta. Maecenas rutrum ipsum rutrum suscipit egestas. <br/><br/>Phasellus venenatis tortor orci, ut feugiat justo efficitur sit amet. Vivamus cursus semper tellus, eget sodales quam tincidunt fermentum. Aenean elementum lobortis felis, eget vehicula lorem sagittis sit amet. Etiam sit amet erat consequat, congue nulla id, iaculis nunc. Donec eleifend libero sit amet turpis volutpat lobortis. Vivamus cursus enim in libero maximus finibus. Pellentesque accumsan laoreet blandit. Phasellus dolor felis, malesuada sit amet sapien vel, congue condimentum tellus. Nulla imperdiet tempor lectus. Etiam fringilla gravida risus id molestie. Phasellus ultrices sed arcu ac semper."
    },
    {
        id: "4",
        route: "/atuacao/4",
        img: img6,
        title: "Consultoria Societária e Contratual",
        description: "A prática de Societário assessora empresas nacionais e internacionais durante todas as fases das negociações em assuntos transacionais e durante todo o ciclo de vida de seus negócios",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel eleifend enim. Sed dictum id justo quis blandit. Suspendisse potenti. Vivamus at dui felis. Morbi sodales, erat eget commodo faucibus, urna tortor sodales nibh, sit amet eleifend orci lectus quis magna. Ut pretium aliquam lorem, a cursus sem vestibulum ac. Sed vulputate, massa ut euismod eleifend, sem eros mattis nulla, sit amet porta ex felis ut diam. <br/><br/>Aenean blandit feugiat ante, a faucibus lacus feugiat varius. Suspendisse tincidunt luctus fringilla. Vivamus sed ipsum ut quam commodo sagittis. Proin posuere sit amet odio eu molestie. Mauris ullamcorper mi a elit posuere dictum. Sed id urna vehicula, mattis libero non, rutrum mauris. Cras eu dolor vitae ex aliquam bibendum in nec augue. Ut sit amet faucibus nulla. Cras magna mauris, lacinia et ex ut, ultricies tincidunt dolor. Etiam viverra faucibus ex, id pharetra lorem ornare in. Quisque sit amet semper tortor. Donec rhoncus diam erat, et lacinia diam mattis id. Fusce cursus diam quis fermentum porta. Maecenas rutrum ipsum rutrum suscipit egestas. <br/><br/>Phasellus venenatis tortor orci, ut feugiat justo efficitur sit amet. Vivamus cursus semper tellus, eget sodales quam tincidunt fermentum. Aenean elementum lobortis felis, eget vehicula lorem sagittis sit amet. Etiam sit amet erat consequat, congue nulla id, iaculis nunc. Donec eleifend libero sit amet turpis volutpat lobortis. Vivamus cursus enim in libero maximus finibus. Pellentesque accumsan laoreet blandit. Phasellus dolor felis, malesuada sit amet sapien vel, congue condimentum tellus. Nulla imperdiet tempor lectus. Etiam fringilla gravida risus id molestie. Phasellus ultrices sed arcu ac semper."
    },
    {
        id: "5",
        route: "/atuacao/5",
        img: img7,
        title: "Propriedade Intelectual",
        description: "Elaboração e negociação de contratos de transferência de tecnologia, cessão de propriedade intelectual, prestação de serviços técnicos, P&D, parcerias e contratos de distribuição.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel eleifend enim. Sed dictum id justo quis blandit. Suspendisse potenti. Vivamus at dui felis. Morbi sodales, erat eget commodo faucibus, urna tortor sodales nibh, sit amet eleifend orci lectus quis magna. Ut pretium aliquam lorem, a cursus sem vestibulum ac. Sed vulputate, massa ut euismod eleifend, sem eros mattis nulla, sit amet porta ex felis ut diam. <br/><br/>Aenean blandit feugiat ante, a faucibus lacus feugiat varius. Suspendisse tincidunt luctus fringilla. Vivamus sed ipsum ut quam commodo sagittis. Proin posuere sit amet odio eu molestie. Mauris ullamcorper mi a elit posuere dictum. Sed id urna vehicula, mattis libero non, rutrum mauris. Cras eu dolor vitae ex aliquam bibendum in nec augue. Ut sit amet faucibus nulla. Cras magna mauris, lacinia et ex ut, ultricies tincidunt dolor. Etiam viverra faucibus ex, id pharetra lorem ornare in. Quisque sit amet semper tortor. Donec rhoncus diam erat, et lacinia diam mattis id. Fusce cursus diam quis fermentum porta. Maecenas rutrum ipsum rutrum suscipit egestas. <br/><br/>Phasellus venenatis tortor orci, ut feugiat justo efficitur sit amet. Vivamus cursus semper tellus, eget sodales quam tincidunt fermentum. Aenean elementum lobortis felis, eget vehicula lorem sagittis sit amet. Etiam sit amet erat consequat, congue nulla id, iaculis nunc. Donec eleifend libero sit amet turpis volutpat lobortis. Vivamus cursus enim in libero maximus finibus. Pellentesque accumsan laoreet blandit. Phasellus dolor felis, malesuada sit amet sapien vel, congue condimentum tellus. Nulla imperdiet tempor lectus. Etiam fringilla gravida risus id molestie. Phasellus ultrices sed arcu ac semper."
    },
    {
        id: "6",
        type: "text",
        title: "Demais especialidades",
        description: "Para outros serviços, entre em contato através do (19) 3296-0715 e consulte a disponibilidade.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel eleifend enim. Sed dictum id justo quis blandit. Suspendisse potenti. Vivamus at dui felis. Morbi sodales, erat eget commodo faucibus, urna tortor sodales nibh, sit amet eleifend orci lectus quis magna. Ut pretium aliquam lorem, a cursus sem vestibulum ac. Sed vulputate, massa ut euismod eleifend, sem eros mattis nulla, sit amet porta ex felis ut diam. <br/><br/>Aenean blandit feugiat ante, a faucibus lacus feugiat varius. Suspendisse tincidunt luctus fringilla. Vivamus sed ipsum ut quam commodo sagittis. Proin posuere sit amet odio eu molestie. Mauris ullamcorper mi a elit posuere dictum. Sed id urna vehicula, mattis libero non, rutrum mauris. Cras eu dolor vitae ex aliquam bibendum in nec augue. Ut sit amet faucibus nulla. Cras magna mauris, lacinia et ex ut, ultricies tincidunt dolor. Etiam viverra faucibus ex, id pharetra lorem ornare in. Quisque sit amet semper tortor. Donec rhoncus diam erat, et lacinia diam mattis id. Fusce cursus diam quis fermentum porta. Maecenas rutrum ipsum rutrum suscipit egestas. <br/><br/>Phasellus venenatis tortor orci, ut feugiat justo efficitur sit amet. Vivamus cursus semper tellus, eget sodales quam tincidunt fermentum. Aenean elementum lobortis felis, eget vehicula lorem sagittis sit amet. Etiam sit amet erat consequat, congue nulla id, iaculis nunc. Donec eleifend libero sit amet turpis volutpat lobortis. Vivamus cursus enim in libero maximus finibus. Pellentesque accumsan laoreet blandit. Phasellus dolor felis, malesuada sit amet sapien vel, congue condimentum tellus. Nulla imperdiet tempor lectus. Etiam fringilla gravida risus id molestie. Phasellus ultrices sed arcu ac semper."
    },
];

export default services;